### ISSUE TITLE
Add a query RPC to get the number of accounts

### ISSUE THREAD

**Issue by ryu1-sakai** [Finschia/finschia-sdk#1001]
## Summary

I home for a new query RPC to get the number of accounts on a chain.

## Problem Definition

LINE Blockchain Explorer needs to know the number of accounts in order to show it on one of its pages.

Originally we planned to get the number using auth.Query.Accounts RPC with PageRequest.count_total = true, but it was found that such counting is too slow (almost 6 minutes in case of Ebony).

Etherscan has the same feature (counting addresses) and may be simply counting addresses which appear in blocks, but it's not very easy for LINE Blockchain Explorer to adopt the same design because:

* In case of Ethereum, there is only one transaction format and Etherscan only needs to monitor 'from' and 'to'. (Probably only 'to' for account generation)
* In case of Finschia, there are a lot of transaction messages and it's not easy for LINK Blockchain Explorer to know all address-related fields and to implement a feature to monitor all of them.
 
## Proposal

Add a new query API to get the latest account number, which is incremental and equal to the current total number of accounts.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zemyblue** [comment]
@ryu1-sakai , do you know how to get the number of accounts on Etherscan?

**Comment by zemyblue** [comment]
There is not the account counting query api. And it is not easy adding this api in current structure. 

Could you count the number of accounts like Etherscan?
In the current version, finschia-sdk v047.0 and finschia v1.0.0, the case to create new account is below. Please monitor it. 

- cosmos.vesting.v1beta1.Msg/CreateVestingAccount 
  - to_address
- cosmos.bank.v1beta1.Msg/MultiSend
  - outputs
- cosmos.feegrant.v1beta1.Msg/GrantAllowance
  - grantee
- cosmos.vesting.v1beta1.Msg/CreateVestingAccount
  - to_address
- cosmwasm.wasm.v1.Msg/InstantiateContract
  - address of respons
- cosmwasm.wasm.v1.Msg/InstantiateContract2
  - address of response

**Comment by zemyblue** [comment]
There is not the account counting query api. However, as we have discussed in other channels, you can estimate the number of accounts by latest `account number`. It is incremented when new account is created in chain. However the `account number` is also incremented when the smart contract is instantiated or when new module or new ibc register is added. 
And now there is not the query api to query the account number. We can add it temporary for LINK Blockchain Explorer for temporary, but please be careful. This is no substitute for account count lookup. And this api will add deprecated annotation because it is temporary api.

Please update the function which count the accounts like Etherscan later.
